<#
.SYNOPSIS
    Generates a Windows Sandbox config for one project and launches it.

.DESCRIPTION
    The day-to-day entry point. The .wsb is regenerated on every launch, so
    edits to the bootstrap script or dotfiles on the host are always picked up.

    The isolation guarantee lives here: exactly one project directory is
    mapped. C:\AgentDev\Projects is never mapped, so an agent inside the
    sandbox has no path to a sibling project, the host user profile, or SSH
    keys.

.PARAMETER Name
    Project directory name under C:\AgentDev\Projects.

.PARAMETER MemoryMB
    Memory for the sandbox. Defaults to 8 GB.

.PARAMETER NoLaunch
    Write the .wsb but do not start the sandbox. Useful for inspecting the
    generated configuration.

.EXAMPLE
    .\Start-Project.ps1 invoice-service
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory, Position = 0)]
    [string]$Name,

    [ValidateRange(2048, 65536)]
    [int]$MemoryMB = 8192,

    [switch]$NoLaunch
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

. (Join-Path $PSScriptRoot 'Common.ps1')

Assert-ProjectName $Name | Out-Null

if (-not (Test-SandboxAvailable)) {
    throw @'
Windows Sandbox is not enabled. From an elevated PowerShell:

    Enable-WindowsOptionalFeature -Online -FeatureName "Containers-DisposableClientVM" -All

then reboot.
'@
}

$projectPath = Join-Path $AgentDev.Projects $Name
if (-not (Test-Path $projectPath)) {
    throw "No such project: $projectPath. Create it with: .\New-Project.ps1 $Name"
}

# Windows Sandbox refuses to start if any HostFolder is missing.
foreach ($dir in @($AgentDev.Sandboxes, "$($AgentDev.Cache)\scoop", "$($AgentDev.Cache)\npm")) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
}
foreach ($required in @($AgentDev.Dotfiles, $AgentDev.Bootstrap)) {
    if (-not (Test-Path $required)) { throw "Missing required directory: $required" }
}

function New-MappedFolder {
    param([string]$HostFolder, [string]$SandboxFolder, [bool]$ReadOnly)
    @"
    <MappedFolder>
      <HostFolder>$([Security.SecurityElement]::Escape($HostFolder))</HostFolder>
      <SandboxFolder>$SandboxFolder</SandboxFolder>
      <ReadOnly>$($ReadOnly.ToString().ToLowerInvariant())</ReadOnly>
    </MappedFolder>
"@
}

$mappings = @(
    (New-MappedFolder $projectPath              'C:\Workspace' $false),
    (New-MappedFolder $AgentDev.Dotfiles        'C:\Dotfiles'  $true),
    (New-MappedFolder $AgentDev.Bootstrap       'C:\Bootstrap' $true),
    (New-MappedFolder $AgentDev.Cache           'C:\Cache'     $false)
) -join "`n"

$wsb = @"
<Configuration>
  <!-- Generated by Start-Project.ps1 for '$Name' on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss').
       Edits are overwritten on the next launch - change Start-Project.ps1 instead. -->
  <VGpu>Disable</VGpu>
  <Networking>Enable</Networking>
  <ProtectedClient>Enable</ProtectedClient>
  <ClipboardRedirection>Enable</ClipboardRedirection>
  <PrinterRedirection>Disable</PrinterRedirection>
  <AudioInput>Disable</AudioInput>
  <VideoInput>Disable</VideoInput>
  <MemoryInMB>$MemoryMB</MemoryInMB>
  <MappedFolders>
$mappings
  </MappedFolders>
  <LogonCommand>
    <Command>powershell.exe -ExecutionPolicy Bypass -NoProfile -File C:\Bootstrap\bootstrap.ps1</Command>
  </LogonCommand>
</Configuration>
"@

$wsbPath = Join-Path $AgentDev.Sandboxes "$Name.wsb"
Set-Content -Path $wsbPath -Value $wsb -Encoding utf8

Write-Host ""
Write-Host "  project   $projectPath"     -ForegroundColor Gray
Write-Host "  config    $wsbPath"         -ForegroundColor Gray
Write-Host "  mapped    C:\Workspace (rw), C:\Dotfiles (ro), C:\Bootstrap (ro), C:\Cache (rw)" -ForegroundColor DarkGray
Write-Host ""

if ($NoLaunch) {
    Write-Host "  Config written. Launch with: Start-Process '$wsbPath'" -ForegroundColor Yellow
    return
}

$running = Get-RunningSandbox
if ($running) {
    throw "A Windows Sandbox is already running (PID $($running.Id)). Only one instance is supported - close it first."
}

Write-Host "  Launching sandbox..." -ForegroundColor Cyan
Start-Process -FilePath (Join-Path $env:WINDIR 'System32\WindowsSandbox.exe') -ArgumentList $wsbPath
