<#
.SYNOPSIS
    Generates a Windows Sandbox config for one project and launches it.

.DESCRIPTION
    The day-to-day entry point. The .wsb is regenerated on every launch, so
    edits to the bootstrap script or dotfiles on the host are always picked up.

    The isolation guarantee lives here: exactly one project directory is
    mapped. C:\AgentDev\Projects is never mapped, so an agent inside the
    sandbox has no path to a sibling project, the host user profile, or SSH
    keys.

.PARAMETER Name
    Project directory name under C:\AgentDev\Projects.

.PARAMETER MemoryMB
    Memory cap for the sandbox. Defaults to all host physical memory. This is
    a cap on dynamic memory, not a reservation, so the sandbox still idles low.

.PARAMETER NoLaunch
    Write the .wsb but do not start the sandbox. Useful for inspecting the
    generated configuration.

.EXAMPLE
    .\Start-Project.ps1 invoice-service
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory, Position = 0)]
    [string]$Name,

    # 0 means "all host physical memory", resolved below. Tracking the host
    # rather than hardcoding a number keeps this correct across hardware
    # changes.
    [int]$MemoryMB = 0,

    [switch]$NoLaunch
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

. (Join-Path $PSScriptRoot 'Common.ps1')

Assert-ProjectName $Name | Out-Null

if (-not (Test-SandboxAvailable)) {
    throw @'
Windows Sandbox is not enabled. From an elevated PowerShell:

    Enable-WindowsOptionalFeature -Online -FeatureName "Containers-DisposableClientVM" -All

then reboot.
'@
}

$projectPath = Join-Path $AgentDev.Projects $Name
if (-not (Test-Path $projectPath)) {
    throw "No such project: $projectPath. Create it with: .\New-Project.ps1 $Name"
}

# Default to the full host memory. MemoryInMB is a ceiling on dynamically
# allocated memory rather than a reservation, so the sandbox still idles low -
# it just never hits an artificial wall during a heavy build.
if ($MemoryMB -le 0) {
    $MemoryMB = [int][math]::Floor((Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory / 1MB)
}
if ($MemoryMB -lt 2048) {
    throw "MemoryMB must be at least 2048 (Windows Sandbox raises anything lower to that minimum anyway)."
}

# Windows Sandbox refuses to start if any HostFolder is missing.
foreach ($dir in @($AgentDev.Sandboxes, "$($AgentDev.Cache)\scoop", "$($AgentDev.Cache)\npm")) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
}
foreach ($required in @($AgentDev.Dotfiles, $AgentDev.Bootstrap, $AgentDev.SharedDotfiles)) {
    if (-not (Test-Path $required)) { throw "Missing required directory: $required" }
}

function New-MappedFolder {
    param([string]$HostFolder, [string]$SandboxFolder, [bool]$ReadOnly)
    @"
    <MappedFolder>
      <HostFolder>$([Security.SecurityElement]::Escape($HostFolder))</HostFolder>
      <SandboxFolder>$SandboxFolder</SandboxFolder>
      <ReadOnly>$($ReadOnly.ToString().ToLowerInvariant())</ReadOnly>
    </MappedFolder>
"@
}

$mappings = @(
    (New-MappedFolder $projectPath              'C:\Workspace'       $false),
    (New-MappedFolder $AgentDev.Dotfiles        'C:\Dotfiles'        $true),
    # The single shared AGENTS.md, mapped separately so this implementation and
    # the active WSL2 one keep reading the same file.
    (New-MappedFolder $AgentDev.SharedDotfiles  'C:\DotfilesShared'  $true),
    (New-MappedFolder $AgentDev.Bootstrap       'C:\Bootstrap'       $true),
    (New-MappedFolder $AgentDev.Cache           'C:\Cache'           $false)
) -join "`n"

$wsb = @"
<Configuration>
  <!-- Generated by Start-Project.ps1 for '$Name' on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss').
       Edits are overwritten on the next launch - change Start-Project.ps1 instead. -->
  <!-- vGPU on: without it all rendering falls back to the WARP software
       rasteriser, which is what makes a GPU-accelerated terminal like WezTerm
       feel sluggish. Microsoft notes this does increase the sandbox attack
       surface. ProtectedClient off: AppContainer isolation adds overhead and
       restricts clipboard transfer, and the isolation that actually matters
       here comes from mapping a single project folder, not from the RDP
       channel. -->
  <VGpu>Enable</VGpu>
  <Networking>Enable</Networking>
  <ProtectedClient>Disable</ProtectedClient>
  <ClipboardRedirection>Enable</ClipboardRedirection>
  <PrinterRedirection>Disable</PrinterRedirection>
  <AudioInput>Disable</AudioInput>
  <VideoInput>Disable</VideoInput>
  <MemoryInMB>$MemoryMB</MemoryInMB>
  <MappedFolders>
$mappings
  </MappedFolders>
  <LogonCommand>
    <Command>powershell.exe -ExecutionPolicy Bypass -NoProfile -File C:\Bootstrap\bootstrap.ps1</Command>
  </LogonCommand>
</Configuration>
"@

$wsbPath = Join-Path $AgentDev.Sandboxes "$Name.wsb"
Set-Content -Path $wsbPath -Value $wsb -Encoding utf8

Write-Host ""
Write-Host "  project   $projectPath"     -ForegroundColor Gray
Write-Host "  config    $wsbPath"         -ForegroundColor Gray
Write-Host "  mapped    C:\Workspace (rw), C:\Dotfiles (ro), C:\DotfilesShared (ro), C:\Bootstrap (ro), C:\Cache (rw)" -ForegroundColor DarkGray
Write-Host ""

if ($NoLaunch) {
    Write-Host "  Config written. Launch with: Start-Process '$wsbPath'" -ForegroundColor Yellow
    return
}

$running = Get-RunningSandbox
if ($running) {
    throw "A Windows Sandbox is already running ($($running.ProcessName), PID $($running.Id)). Only one instance is supported - close it first."
}

Write-Host "  Launching sandbox..." -ForegroundColor Cyan

$process = Start-Process -FilePath (Join-Path $env:WINDIR 'System32\WindowsSandbox.exe') `
                         -ArgumentList $wsbPath -PassThru

# WindowsSandbox.exe returns immediately on success but also exits immediately
# when it refuses to start - most often because a previous session is still
# tearing down. Without this check the failure is completely silent.
Start-Sleep -Seconds 5
if ($process.HasExited -and $process.ExitCode -ne 0) {
    throw "Windows Sandbox failed to start (exit code $($process.ExitCode)). If a sandbox was just closed, wait a few seconds for teardown and try again."
}

if (-not (Get-RunningSandbox)) {
    Write-Warning 'No sandbox process detected yet - it may still be starting. If no window appears, re-run this command.'
} else {
    Write-Host "  Sandbox starting. Bootstrap progress:" -ForegroundColor Green
    Write-Host "    Get-Content '$projectPath\.agentdev-bootstrap.log' -Wait -Tail 20" -ForegroundColor DarkGray
}
